### ISSUE TITLE
Handle/Consider new segment ID format

### ISSUE THREAD

**Issue by nelsonjchen** [nelsonjchen/op-replay-clipper#69]
https://github.com/commaai/connect/pull/449

**Comment by jplehmann** [comment]
Is this the reason why my attempt to use this is failing?

input: https://connect.comma.ai/xxx/yyy--zzz

```
NOTES:
Number of url parts:  3
Traceback (most recent call last):
File "/root/.pyenv/versions/3.12.5/lib/python3.12/site-packages/cog/server/worker.py", line 349, in _predict
result = predict(**payload)
^^^^^^^^^^^^^^^^^^
File "/src/predict.py", line 111, in predict
parsed_input_route_or_url = route_or_url.parseRouteOrUrl(
```

I don't understand though, because the readme says:
"Note: comma has changed the URL format since this step was originally written. New URLs are like..." which means it seems like it should work.
